### ISSUE TITLE
SSL

### ISSUE THREAD

**Issue by ardydavari** [pawamoy/docker-nginx-postgres-django-example#2]
Thank you for your excellent repo.

Just making a request for instructions regarding configuring SSL.

**Comment by pawamoy** [comment]
Hmm, I somehow forgot to reply to this. I don't have time these days to update the post to include SSL configuration, but I guess I would do it with Let's Encrypt. Anyway, leaving this open as this would be a neat addition :slightly_smiling_face:

**Comment by pawamoy** [comment]
Won't likely update anything, closing :confused:
