### ISSUE TITLE
Support for django channels

### ISSUE THREAD

**Issue by nikolas-dev** [pawamoy/docker-nginx-postgres-django-example#5]
Is there any plan supporting for django channels

**Comment by pawamoy** [comment]
I'm not sure what you mean by "support". This repo is just an example to get started with Docker and Django. Are you asking for another example repo with Docker and Django Channels? If so, sorry but my knowledge of Django Channels is... very limited.

Also worth noting: Django 3 has support for asynchronous code/views!

**Comment by nikolas-dev** [comment]
yes. example repo with docker and django channels

**Comment by pawamoy** [comment]
Well sorry but I don't have the skills or time for it :sweat_smile: Closing since there's nothing more I can do here!
