### ISSUE TITLE
Updating packages

### ISSUE THREAD

**Issue by oliverilm** [pawamoy/docker-nginx-postgres-django-example#8]
Update all dependencies to their latest version ? Or is there a simple way to do this. My first guess would be to go after the Pipfile.lock file. to do this manually. Can it be automated or does it have to be done by hand (replacing the versions and the hashes)?

**Comment by pawamoy** [comment]
Not sure about pipenv, I'm using poetry these days :sweat_smile:! But I don't think either of them as the ability to update the pyproject.toml or Pipfile automatically to update version (I do have an ugly Python script to do that for Poetry though, if you're interested). I think you'd have better luck with https://pyup.io/ or something equivalent.

I don't want to update the Pipfile in this repo, so I'm closing this, but if you want to send a PR I'll gladly accept it!
